#!/bin/bash

set -e
set -x

which apt-get > /dev/null 2>&1 && {
   echo "Installing Docker for Debian"
   curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
   sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
   sudo apt-get update
   sudo apt-cache policy docker-ce
   sudo apt-get install -y docker-ce
   sudo systemctl start docker
   sudo systemctl enable docker
   exit 0
}

which yum > /dev/null 2>&1 && {
   echo "Installing Docker for Fedora"
   sudo yum -y install curl
   sudo curl -o /etc/yum.repos.d/docker-ce.repo https://download.docker.com/linux/fedora/docker-ce.repo
   sudo yum -y install docker-ce
   sudo systemctl start docker
   sudo systemctl enable docker
   exit 0
}

echo "Not installed, system type unknown"
exit 1
